/** Inspect 属性面板：Vue prop key → 中文标题（未入 catalog 的 Eg* 组件 fallback）。 */
const INSPECT_PROP_LABELS: Record<string, string> = {
  active: '选中',
  align: '对齐',
  as: '元素类型',
  badge: '角标',
  batchActions: '批操作',
  batchCountSuffix: '统计后缀',
  batchPopoverTopTool: 'Popover 顶栏',
  batchPopoverTopToolClosable: '顶栏可关闭',
  batchPopoverTopToolTitle: '顶栏标题',
  batchPopoverWidth: 'Popover 宽度',
  batchPopoverWidthMode: 'Popover 宽度模式',
  blank: '空白列',
  border: '边框',
  color: '颜色',
  columnHeight: '列高',
  content: '内容',
  customStyle: '自定义样式',
  data: '行数据',
  dataList: '列表数据',
  disabled: '禁用',
  displayOrder: '展示顺序',
  displayText: '展示文本',
  emptyText: '空态文案',
  family: '系列',
  fit: '适应容器',
  flexGrow: '弹性均分',
  headerBg: '表头背景',
  headerHeight: '表头高度',
  heightMode: '高度模式',
  hidden: '隐藏',
  hideActions: '隐藏操作',
  href: '链接',
  iconPosition: '图标位置',
  index: '索引',
  initing: '初始化中',
  isAction: '操作列',
  label: '标签',
  loading: '加载中',
  max: '最大值',
  maxHeight: '最大高度',
  minTableWidth: '最小表格宽度',
  minWidth: '最小宽度',
  moreActions: '更多操作',
  motion: '动效',
  name: '名称',
  panelKind: '面板类型',
  panelMicroFloat: '微浮动',
  panelRadius: '面板圆角',
  placement: '位置',
  primaryAction: '主操作',
  prop: '字段',
  scrollable: '可滚动',
  selected: '已选',
  selectMode: '多选模式',
  shape: '形状',
  showBadge: '显示角标',
  showOverflowTooltip: '溢出 Tooltip',
  showReddot: '显示红点',
  size: '尺寸',
  skidOpen: 'Skid 打开',
  sortable: '可排序',
  status: '状态',
  systemType: '系统类型',
  tabular: '等宽数字',
  text: '文本',
  tone: '色调',
  truncate: '截断',
  type: '类型',
  value: '数值',
  variant: '变体',
  width: '宽度',
  widthMode: '宽度模式',
  widthPercent: '宽度占比',
};

export function resolveInspectPropLabel(key: string): string {
  return INSPECT_PROP_LABELS[key] ?? key;
}
