/** Cregis Nav Bar 声明式 props — 与 eds-desktop Showcase 默认窄版（74px）一致。 */
export const cregisNavBarDeclarativeAttrs = {
  moduleCount: 8,
  appEntryCount: 2,
  corporationLabel: 'G',
  avatarInitials: 'A',
  moduleLabel1: 'Wallet',
  moduleLabel2: 'Tasks',
  moduleLabel3: 'WaaS',
  moduleLabel4: 'Payment Engine',
  moduleLabel5: 'Report',
  moduleLabel6: 'Risk Control',
  moduleLabel7: 'Manage',
  moduleLabel8: 'Marketplace',
  moduleIcon1: 'eds-wallet',
  moduleFocusIcon1: 'eds-wallet-fill',
  moduleIcon2: 'eds-circulation',
  moduleFocusIcon2: 'eds-circulation-fill',
  moduleIcon3: 'eds-floder-favorite',
  moduleFocusIcon3: 'eds-floder-favorite-fill',
  moduleIcon4: 'eds-global-payments',
  moduleFocusIcon4: 'eds-global-payments-fill',
  moduleIcon5: 'eds-bill',
  moduleFocusIcon5: 'eds-bill-fill',
  moduleIcon6: 'eds-database-safety',
  moduleFocusIcon6: 'eds-database-safety-fill',
  moduleIcon7: 'eds-categorization',
  moduleFocusIcon7: 'eds-categorization-fill',
  moduleIcon8: 'eds-app-ecology',
  moduleFocusIcon8: 'eds-app-ecology-fill',
  appEntryLabel1: 'UniChain',
  appEntryIcon1: 'eds-application-22',
  appEntryFocusIcon1: 'eds-application-22',
  appEntryLabel2: 'MetaMask',
  appEntryIcon2: 'eds-application-5',
  appEntryFocusIcon2: 'eds-application-5',
} as const;
